// Compiled shader for PC, Mac & Linux Standalone, uncompressed size: 4.5KB

// Skipping shader variants that would not be included into build of current scene.

Shader "Hidden/kode80/CloudBlender" {
Properties {
 _MainTex ("Base (RGB)", 2D) = "white" { }
}
SubShader { 
 Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 2 math
 //        d3d9 : 6 math
 // Stats for Fragment shader:
 //       d3d11 : 3 math, 1 texture
 //        d3d9 : 10 math, 1 texture
 Pass {
  Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }
  ZWrite Off
  Cull Off
  Blend One OneMinusSrcAlpha
  GpuProgramID 13194
Program "vp" {
SubProgram "d3d9 " {
// Stats: 6 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Vector 0 [_ProjectionParams]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   float4 _ProjectionParams;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   _ProjectionParams c0       1
//

    vs_3_0
    def c1, 0, -2, 1, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    mov r0.x, c1.x
    slt r0.x, c0.x, r0.x
    mad r0.y, v1.y, c1.y, c1.z
    mad o1.y, r0.x, r0.y, v1.y
    mad o0, v0.xyzx, c1.zzzx, c1.xxxz
    mov o1.x, v1.x

// approximately 6 instruction slots used
"
}
SubProgram "d3d11 " {
// Stats: 2 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "UnityPerCamera" 144
Vector 80 [_ProjectionParams]
BindCB  "UnityPerCamera" 0
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xyzw        2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
      vs_4_0
      dcl_constantbuffer cb0[6], immediateIndexed
      dcl_input v0.xyz
      dcl_input v2.xy
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xy
      dcl_temps 1
   0: mov o0.xyz, v0.xyzx
   1: mov o0.w, l(1.000000)
   2: lt r0.x, cb0[5].x, l(0.000000)
   3: add r0.y, -v2.y, l(1.000000)
   4: movc o1.y, r0.x, r0.y, v2.y
   5: mov o1.x, v2.x
   6: ret 
// Approximately 0 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 10 math, 1 textures
Float 0 [_IsGamma]
SetTexture 0 [_MainTex] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   bool _IsGamma;
//   sampler2D _MainTex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   _IsGamma     c0       1
//   _MainTex     s0       1
//

    ps_3_0
    def c1, 2.20000005, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld_pp r0, v0, s0
    log_pp r1.x, r0.x
    log_pp r1.y, r0.y
    log_pp r1.z, r0.z
    log_pp r1.w, r0.w
    mul_pp r1, r1, c1.x
    exp_pp r2.x, r1.x
    exp_pp r2.y, r1.y
    exp_pp r2.z, r1.z
    exp_pp r2.w, r1.w
    cmp_pp oC0, -c0.x, r2, r0

// approximately 11 instruction slots used (1 texture, 10 arithmetic)
"
}
SubProgram "d3d11 " {
// Stats: 3 math, 1 textures
SetTexture 0 [_MainTex] 2D 0
ConstBuffer "$Globals" 112
ScalarBool 96 [_IsGamma]
BindCB  "$Globals" 0
"//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer cb0[7], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v1.xy
      dcl_output o0.xyzw
      dcl_temps 2
   0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
   1: log r1.xyzw, r0.xyzw
   2: mul r1.xyzw, r1.xyzw, l(2.200000, 2.200000, 2.200000, 2.200000)
   3: exp r1.xyzw, r1.xyzw
   4: movc o0.xyzw, cb0[6].xxxx, r0.xyzw, r1.xyzw
   5: ret 
// Approximately 0 instruction slots used
"
}
}
 }
}
}